# coding: utf-8

"""
    API de gestion de contenu des cours en ligne

    Voici mon API REST pour gérer les cours, les séances et les fichiers associés à ceux-ci  # noqa: E501

    OpenAPI spec version: 1.0.11
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from setuptools import setup, find_packages  # noqa: H301

NAME = "swagger-client"
VERSION = "1.0.0"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = [
    "certifi>=2017.4.17",
    "python-dateutil>=2.1",
    "six>=1.10",
    "urllib3>=1.23"
]
    

setup(
    name=NAME,
    version=VERSION,
    description="API de gestion de contenu des cours en ligne",
    author_email="",
    url="",
    keywords=["Swagger", "API de gestion de contenu des cours en ligne"],
    install_requires=REQUIRES,
    packages=find_packages(),
    include_package_data=True,
    long_description="""\
    Voici mon API REST pour gérer les cours, les séances et les fichiers associés à ceux-ci  # noqa: E501
    """
)
