# coding: utf-8

"""
    API de gestion de contenu des cours en ligne

    Voici mon API REST pour gérer les cours, les séances et les fichiers associés à ceux-ci  # noqa: E501

    OpenAPI spec version: 1.0.11
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.seance_api import SeanceApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSeanceApi(unittest.TestCase):
    """SeanceApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.seance_api.SeanceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_seance(self):
        """Test case for create_seance

        création d'une seance  # noqa: E501
        """
        pass

    def test_delete_seance(self):
        """Test case for delete_seance

        Suppression d'une seance d'un cours  # noqa: E501
        """
        pass

    def test_find_seance(self):
        """Test case for find_seance

        Trouver une seance selon ID spécifique  # noqa: E501
        """
        pass

    def test_seance_find_by_module(self):
        """Test case for seance_find_by_module

        Trouver la séance selon un module spécifique  # noqa: E501
        """
        pass

    def test_seance_find_by_semaine(self):
        """Test case for seance_find_by_semaine

        Trouver la séance selon une semaine  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
