# coding: utf-8

"""
    API de gestion de contenu des cours en ligne

    Voici mon API REST pour gérer les cours, les séances et les fichiers associés à ceux-ci  # noqa: E501

    OpenAPI spec version: 1.0.11
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.cours_api import CoursApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCoursApi(unittest.TestCase):
    """CoursApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.cours_api.CoursApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_cours(self):
        """Test case for add_cours

        Add a new cours  # noqa: E501
        """
        pass

    def test_delete_cours(self):
        """Test case for delete_cours

        Delete cours  # noqa: E501
        """
        pass

    def test_find_cours_by_id(self):
        """Test case for find_cours_by_id

        Finds cours by ID  # noqa: E501
        """
        pass

    def test_find_cours_by_tags(self):
        """Test case for find_cours_by_tags

        Finds cours by tags  # noqa: E501
        """
        pass

    def test_update_cours(self):
        """Test case for update_cours

        Modification d'un cours existant  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
