# coding: utf-8

# flake8: noqa

"""
    API de gestion de contenu des cours en ligne

    Voici mon API REST pour gérer les cours, les séances et les fichiers associés à ceux-ci  # noqa: E501

    OpenAPI spec version: 1.0.11
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import apis into sdk package
from swagger_client.api.cours_api import CoursApi
from swagger_client.api.seance_api import SeanceApi

# import ApiClient
from swagger_client.api_client import ApiClient
from swagger_client.configuration import Configuration
# import models into sdk package
